# Generated by Django 2.2.4 on 2020-08-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Terminal', models.CharField(max_length=20)),
                ('Fecha', models.CharField(max_length=20)),
                ('Hora', models.CharField(max_length=20)),
                ('Evento', models.CharField(max_length=50)),
                ('Locacion', models.CharField(max_length=50)),
                ('EntryID', models.CharField(max_length=300)),
            ],
        ),
    ]
