# Generated by Django 2.2.4 on 2020-08-06 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='Activo',
            field=models.BooleanField(default=True),
        ),
    ]
