# Generated by Django 3.1.2 on 2021-02-09 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_auto_20201013_1004'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NroSerie', models.CharField(max_length=30)),
                ('Numero', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='ticket',
            name='Terminal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tickets.cajero'),
        ),
    ]
