# Generated by Django 3.1.2 on 2021-02-09 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_auto_20210209_0027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='Terminal',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Cajero',
        ),
    ]
